### ISSUE TITLE
Server complains when market gardener and gunboats are disabled

### ISSUE THREAD

**Issue by Hnaguski** [CammiesCorner/Firework-Frenzy#1]
I have Firework Frenzy installed on my server, but with the market gardener and gunboats disabled. This causes some errors in the console.
[server log](https://paste.nilsu.org/b7db4c1ae6472eeae3497f081899531ed6c20f47.log
)

**Comment by CammiePone** [comment]
It's just recipe stuff. It's not really a problem. Game will run just fine
