### ISSUE TITLE
Where are Rubber boots that allow no fall damage while Rocket Jumping?

### ISSUE THREAD

**Issue by RedWideWeb** [CammiesCorner/Firework-Frenzy#12]
I am on version 1.9 for 1.18.2. I can't find these boots in creative. I have Rocket Jumping turned ON in config
![2022-08-04_12 11 04](https://user-images.githubusercontent.com/58992150/182810535-a71fd731-86fa-4f2b-86e9-40cca2e1e2ca.png)

**Comment by CammiePone** [comment]
removed

**Comment by RedWideWeb** [comment]
> removed

How to Rocket jump then?

**Comment by CammiePone** [comment]
you just do it and deal with taking damage. there's an enchant that makes it so you wont take rocket damage from jumping, but you'll still take fall damage. it's mutually exclusive to feather falling, so you either take damage at the beginning or end of your jump. up to you

**Comment by RedWideWeb** [comment]
> you just do it and deal with taking damage. there's an enchant that makes it so you wont take rocket damage from jumping, but you'll still take fall damage. it's mutually exclusive to feather falling, so you either take damage at the beginning or end of your jump. up to you

What is the enchant?

**Comment by CammiePone** [comment]
it's called jumper specialist, you can find it in the combat tab

**Comment by RedWideWeb** [comment]
The shield kinda either blocks all damage or no damage at all. Is that a bug?
https://user-images.githubusercontent.com/58992150/182824979-ec7fb325-13cd-4c81-9a13-4c17a6c8bed3.mp4

**Comment by RedWideWeb** [comment]
So the first try was direct hit and second is ground hit

**Comment by CammiePone** [comment]
most likely the entity exploded inside the player's hitbox, thus going around the shield. I dont do anything special there, that's just vanilla

**Comment by RedWideWeb** [comment]
> most likely the entity exploded inside the player's hitbox, thus going around the shield. I dont do anything special there, that's just vanilla

So you say vanilla fireworks can be completely blocked by a shield? Crap

okay thank you very much for such a fast response and please mention on curseforge that this mod adds this enchantment

**Comment by CammiePone** [comment]
shields are overpowered, of course they can block a firework

**Comment by RedWideWeb** [comment]
> shields are overpowered, of course they can block a firework

I mean without loosing durability
