### ISSUE TITLE
Self-damage no longer gives invincibility frames

### ISSUE THREAD

**Issue by RedWideWeb** [CammiesCorner/Firework-Frenzy#14]
Is it possible to completely remove invincibility frames for any type of damage?

**Comment by CammiePone** [comment]
that's already done, it's just a small tweak to prevent you from making yourself unkillable for a short while :p

**Comment by RedWideWeb** [comment]
> that's

Is there a mod?

**Comment by CammiePone** [comment]
I mean it's already in the mod. self-damage from fireworks wont give you invulnerability ticks

**Comment by RedWideWeb** [comment]
> I mean it's already in the mod. self-damage from fireworks wont give you invulnerability ticks

But can you make it so that from any damage there are no invincibility frames? I want to shoot 2 arrows at the same time into a mob with my friend and kill it

**Comment by CammiePone** [comment]
Cammie's Combat Tweaks does that, but it's got some kinks to work out still
