### ISSUE TITLE
Make explosive fireworks... explosive.

### ISSUE THREAD

**Issue by mettlephaontoms** [CammiesCorner/Firework-Frenzy#16]
Add an option to the config file to enable a value of explosion power for explosive rockets, currently there is no other up to date mod for Fabric 1.19 which has this functionality. I was hoping that this mod would not only have practical firework weapons but also this explosive functionality.

**Comment by CammiePone** [comment]
I considered this, but didn't think anyone would actually want it. I can add it though!
