### ISSUE TITLE
Error in logs: Parsing error loading recipe fireworkfrenzy:market_gardener and fireworkfrenzy:gunboats

### ISSUE THREAD

**Issue by GameDokter51** [CammiesCorner/Firework-Frenzy#17]
I keep seeing an error pop up in the logs about the game being unable to load the recipe for items called the Market Gardener and Gunboat. Also, the game log is full of OpenGL errors with the IDs 1281 and 1282. I don't know if that is related to firework frenzy, but I thought I would mention it because it's really getting annoying and I am noticing a performance decrease.
[latest.log](https://github.com/CammiePone/FireworkFix/files/10108156/latest.log)

**Comment by CammiePone** [comment]
the opengl errors definitely arent, I dont touch rendering code at all with this mod. the recipe errors are benign, but easy to fix on my end
