### ISSUE TITLE
can i publish 1.20.1 version?

### ISSUE THREAD

**Issue by Volery39** [CammiesCorner/Firework-Frenzy#18]
i have updated this mod to 1.20.1 for personal use but can i publish it on curseforge since it's been 4 months since the last update?

**Comment by bruglet** [comment]
Maybe ask on the [discord](https://discord.gg/f5dFYWX), Cammie (The dev of this mod) is done with modding so it might be possible that this github page won't be checked anymore.

**Comment by CammiePone** [comment]
i have ported it at this point, and it'll be released soon ish once it's also been ported to neoforge

**Comment by MarkCauldronG** [comment]
> i have ported it at this point, and it'll be released soon ish once it's also been ported to neoforge

will it be available for regular forge? i dont want to use sinytra connector just to use this awesome mod

**Comment by ihymyly** [comment]
Will a Fabric version be available?

edit: for 1.20.1

**Comment by CammiePone** [comment]
> will it be available for regular forge? i dont want to use sinytra connector just to use this awesome mod

> Will a Fabric version be available?
> 
> edit: for 1.20.1

the answer to both is no, because NeoForge runs Forge mods in 1.20.1 and Quilt runs Fabric mods always so there's no point in double double the work
