### ISSUE TITLE
Gunboats and Market Gardener

### ISSUE THREAD

**Issue by Semmad** [CammiesCorner/Firework-Frenzy#2]
How do I use the Gunboats and Market Gardener? Ive played around with them both in creative and survival and cannot for the life of me figure out how to use them. I have them activated in the mods configs on server side and client but just don't know how to use the rocket functionalities.

**Comment by CammiePone** [comment]
![image](https://user-images.githubusercontent.com/16853086/155011004-e810730f-cbdb-4783-8dd4-afbe024c3a33.png)

**Comment by Semmad** [comment]
Thank you so much! One last question, how does one rocket jump? I'm sorry for all the questions
