### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by woodiertexas** [CammiesCorner/Firework-Frenzy#4]
For different firework types, refer to this:https://youtu.be/HU7eHQzTKD8?t=143

Firework Launching Stuff
- Multi-firework launcher (like the dispenser but launches multiple rockets at the same time)
- Mortar Shell Launcher
- Multi-shell Launcher (like the mortar shell launcher but launches multiple shells at the same time)

Misc. Tweaks
- Have fireworks shot from the firework launching stuff and vanilla dispenser veer off in a random direction before exploding just like player-launched fireworks do

**Comment by mettlephaontoms** [comment]
Enable explosive fireworks to destroy a configurable amount of terrain {power 1-2 by default.}
