### ISSUE TITLE
Doesn't Do/Add Anything?

### ISSUE THREAD

**Issue by pawbap** [CammiesCorner/Firework-Frenzy#5]
I don't know what I'm doing wrong. I'm running the latest version of everything, tried running an instance where only Firework Frenzy and its dependencies are installed, but when I get into the game, there's no mention of a Firework Frenzy mod/items/any tweaks to the crossbow+firework interactions besides the config menu if I install ModMenu as well.

I'm like 99% sure this is unintentional???

**Comment by pawbap** [comment]
Oh, and this is 1.18.2 by the way.

**Comment by CammiePone** [comment]
That's because there aren't any items. There's a single enchantment you can find called Jumper Specialist (I'm bad with names) though

**Comment by pawbap** [comment]
Oh sorry. I misunterstood what this mod added. Very cool now that I know, though!
